# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: poetic_proto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='poetic_proto.proto',
  package='poetic',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12poetic_proto.proto\x12\x06poetic\"\x18\n\x05Query\x12\x0f\n\x07request\x18\x01 \x01(\t\"\x18\n\x06\x41nswer\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t25\n\x06Poetic\x12+\n\x08generate\x12\r.poetic.Query\x1a\x0e.poetic.Answer\"\x00\x62\x06proto3')
)




_QUERY = _descriptor.Descriptor(
  name='Query',
  full_name='poetic.Query',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='poetic.Query.request', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=54,
)


_ANSWER = _descriptor.Descriptor(
  name='Answer',
  full_name='poetic.Answer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='answer', full_name='poetic.Answer.answer', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=80,
)

DESCRIPTOR.message_types_by_name['Query'] = _QUERY
DESCRIPTOR.message_types_by_name['Answer'] = _ANSWER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Query = _reflection.GeneratedProtocolMessageType('Query', (_message.Message,), dict(
  DESCRIPTOR = _QUERY,
  __module__ = 'poetic_proto_pb2'
  # @@protoc_insertion_point(class_scope:poetic.Query)
  ))
_sym_db.RegisterMessage(Query)

Answer = _reflection.GeneratedProtocolMessageType('Answer', (_message.Message,), dict(
  DESCRIPTOR = _ANSWER,
  __module__ = 'poetic_proto_pb2'
  # @@protoc_insertion_point(class_scope:poetic.Answer)
  ))
_sym_db.RegisterMessage(Answer)



_POETIC = _descriptor.ServiceDescriptor(
  name='Poetic',
  full_name='poetic.Poetic',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=82,
  serialized_end=135,
  methods=[
  _descriptor.MethodDescriptor(
    name='generate',
    full_name='poetic.Poetic.generate',
    index=0,
    containing_service=None,
    input_type=_QUERY,
    output_type=_ANSWER,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_POETIC)

DESCRIPTOR.services_by_name['Poetic'] = _POETIC

# @@protoc_insertion_point(module_scope)
