# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import poetic_proto_pb2 as poetic__proto__pb2


class PoeticStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.generate = channel.unary_unary(
        '/poetic.Poetic/generate',
        request_serializer=poetic__proto__pb2.Query.SerializeToString,
        response_deserializer=poetic__proto__pb2.Answer.FromString,
        )


class PoeticServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def generate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PoeticServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'generate': grpc.unary_unary_rpc_method_handler(
          servicer.generate,
          request_deserializer=poetic__proto__pb2.Query.FromString,
          response_serializer=poetic__proto__pb2.Answer.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'poetic.Poetic', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
